# Generated by Django 2.0.13 on 2019-03-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190320_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='qtdEmbalagem',
        ),
    ]
